# baseurl: 'https://www.squizduos.ru/'
title: Squizduos Slowblog
copyright: '&copy; 2019 squizduos'
canonifyurls: true
paginate: 10
languageCode: ru-ru
theme: squizduos
paginate: 5

permalinks:
  post: '/blog/:filename/'
  
indexes:
  tag: tags
  topic: topics

params:
  author: Semyon Bochkaryov
  email: squizduos@gmail.com
  subtitle: 'High tech, low life'
  googleAnalytics: UA-64612974-1
  disqus: squizduos
  highlightjs: monokai
  dateFormat: '02.01.2006 15:04'
  sideMenu:
    topics: 10
    parental: true
    buildInfo: true
  topics: 10
  parental: true
  buildinfo: true
  contacts:
    - name: Telegram
      icon: fa-telegram
      weight: 1
      url: https://telete.in/squizduos
    - name: ВКонтакте
      icon: fa-vk
      weight: 2
      url: https://vk.com/squizduos
    - name: Twitter
      icon: fa-twitter-square
      weight: 3
      url: https://twitter.com/squizduos
    - name: Instagram
      icon: fa-instagram
      weight: 4
      url: https://instagram.com/squizduos
    - name: LinkedIn
      icon: fa-linkedin
      weight: 5
      url: https://linkedin.com/in/squizduos
    - name: GitHub
      icon: fa-github-square
      weight: 6
      url: https://github.com/squizduos
    - name: GitLab
      icon: fa-gitlab
      weight: 7
      url: https://git.squizduos.com/
  custom_css:
    - css/pc-tab.css
    - css/modal.css
menu:
  main:
    - name: Главная
      pre: <i class='fa fa-home fa-fw'></i>
      weight: 1
      identifier: home
      url: /
    # - name: Проекты
    #   pre: <i class='fa fa-desktop fa-fw'></i>
    #   weight: 3
    #   identifier: projects
    #   url: /projects/
    # - name: Заметки
    #   pre: <i class='fas fa-sticky-note fa-fw'></i>
    #   weight: 4
    #   identifier: notes
    #   url: /notes/
    - name: Работа
      pre: <i class="fas fa-file-alt fa-fw"></i>
      weight: 5
      url: /hire/
    - name: Channel 11
      pre: <i class='fab fa-telegram fa-fw'></i>
      weight: 6
      url: https://telete.in/ch_11
