baseurl: 'https://www.squizduos.ru/'
title: Squizduos Slowblog
copyright: '&copy; 2019 squizduos'
canonifyurls: true
paginate: 10
languageCode: ru-ru
theme: squizduos

permalinks:
  post: '/blog/:filename/'
  
indexes:
  tag: tags
  topic: topics

params:
  author: Semyon Bochkaryov
  subtitle: 'High tech, low life'
  brand: squizduos.ru
  googleAnalytics: UA-64612974-1
  disqus: squizduos
  highlightjs: androidstudio
  dateFormat: '02.01.2006 15:04'

menu:
  main:
    - name: Главная
      pre: <i class='fa fa-home fa-fw'></i>
      weight: 1
      identifier: home
      url: /
    - name: Проекты
      pre: <i class='fa fa-desktop fa-fw'></i>
      weight: 2
      identifier: topic
      url: /projects/
    - name: О блоге
      pre: <i class='fa fa-phone fa-fw'></i>
      weight: 3
      url: /about/
  blogs:
  - name: Channel 11
    pre: <i class='fab fa-telegram fa-fw'></i>
    weight: 1
    url: 'https://tlg.name/ch_11'
  - name: Nova the Hedgehog
    pre: <i class='fab fa-twitter-square fa-fw'></i>
    weight: 2
    url: 'https://twitter.com/squizduos'

social:
  vk: squizduos
  linkedin: squizduos
  github: squizduos
  bitbucket: squizduos
